<a href="https://colab.research.google.com/github/241801505/Machine-Learning/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5])
print (arr)

[1 2 3 4 5]


In [ ]:
import sys
S= range(1000)
print("size of each element of list in bytes:",sys.getsizeof(S))
print("size of the whole list in bytes:",sys.getsizeof(S)*len(S))
D=np.arange(1000)
print("size of each element of the numpy array in bytes:",D.itemsize)
print("size of the whole numpy array in bytes:",D.size*D.itemsize)


size of each element of list in bytes: 48
size of the whole list in bytes: 48000
size of each element of the numpy array in bytes: 8
size of the whole numpy array in bytes: 8000


In [ ]:
arr=np.array(42)
print(arr)


42


In [ ]:
arr=np.array([[1,2,3],[4,5,6]])
print (arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
arr=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print (arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [ ]:
zeros_arr=np.zeros((5,2))
eros_arr=np.zeros(5)
print(zeros_arr)
zeros_arr=np.zeros((2,3))
print(zeros_arr)
print("data type of the array:",zeros_arr.dtype)
zeros_arr_int=np.zeros((3,3),dtype=np.int16)
print("\narray of zeros with integer elements :\n",zeros_arr_int)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]]
data type of the array: float64

array of zeros with integer elements :
 [[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
ones_arr=np.ones(6)
print(ones_arr)
print("\ndata type of the array:",ones_arr.dtype)

[1. 1. 1. 1. 1. 1.]

data type of the array: float64


In [ ]:
empty_arr=np.empty((3,2))
print(empty_arr)
print("\ndata type of the array:",empty_arr.dtype)

[[1. 1.]
 [1. 1.]
 [1. 1.]]

data type of the array: float64


In [ ]:
identity_matrix=np.eye(3)
print(identity_matrix)
identity_matrix=np.eye(4)
print("\n",identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
arr1=np.array([1,2,3],dtype=np.float64)
arr2=np.array([1,2,3],dtype=np.int32)
print(arr1.dtype)
print(arr2.dtype)

float64
int32


In [ ]:
arr=np.array([1,2,3])
print("before converting:",arr,arr.dtype)
new_arr=arr.astype("f")
print("after converting:", new_arr,new_arr.dtype)

before converting: [1 2 3] int64
after converting: [1. 2. 3.] float32


In [ ]:
arr1=np.arange(10)
arr2=np.random.randn(10)
print("array 1\n",arr1, arr1.dtype)
print("array2\n",arr2,arr2.dtype)
print("new array\n", new_arr,new_arr.dtype)

array 1
 [0 1 2 3 4 5 6 7 8 9] int64
array2
 [-0.5882432   0.58826148 -0.88837066 -1.11555435  0.57673078 -0.33259999
 -0.82075516  0.64694969 -0.54432894  0.31916361] float64
new array
 [1. 2. 3.] float32


In [ ]:
str_arr=np.array(["hello","world","numpy"])
print(str_arr)

['hello' 'world' 'numpy']


In [ ]:
a=np.array([1.,2.,3.,4.])
b=np.array([5.,6.,7.,8.])
print(a+b)#[6 8 10 12]
print(a-b)#[-4 -4 -4 -4]
print(a*b)#[5 12 21 32]
print(a/b)#[0.2  0.33333333  0.42857143  0.5 ]
print(a**b)#[ 1  64  2187  65536]

[ 6.  8. 10. 12.]
[-4. -4. -4. -4.]
[ 5. 12. 21. 32.]
[0.2        0.33333333 0.42857143 0.5       ]
[1.0000e+00 6.4000e+01 2.1870e+03 6.5536e+04]


In [ ]:
import numpy as np
arr=np.arange(12)
newarr=arr.reshape(4,3)
print(newarr)
newarr=arr.reshape((4,3),order="F")
print("\n",newarr)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [ ]:
import numpy as np
arr=np.array([[1,2,3,4,8,10],[5,6,7,8,11,12]])
print(arr)
newarr=arr.reshape(3,2,2)
print("\n",newarr)
newarr1=newarr.reshape(3,-1)
print("\n reshape(3,-1)\n",newarr1)


[[ 1  2  3  4  8 10]
 [ 5  6  7  8 11 12]]

 [[[ 1  2]
  [ 3  4]]

 [[ 8 10]
  [ 5  6]]

 [[ 7  8]
  [11 12]]]

 reshape(3,-1)
 [[ 1  2  3  4]
 [ 8 10  5  6]
 [ 7  8 11 12]]


In [ ]:
import numpy as np

original_array = np.array([[10, 20], [30, 40]])
print("Original array:\n", original_array)

flattened_array = original_array.flatten()
flattened_array[0] = 999
print("Flattened array:\n", flattened_array)
print("Original array:\n", original_array)

raveled_array = original_array.ravel()
raveled_array[1] = 888

print("Raveled array:\n", raveled_array)
print("Original array:\n", original_array)

Original array:
 [[10 20]
 [30 40]]
Flattened array:
 [999  20  30  40]
Original array:
 [[10 20]
 [30 40]]
Raveled array:
 [ 10 888  30  40]
Original array:
 [[ 10 888]
 [ 30  40]]


In [ ]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[2, 1], [3, 5]])

greater_than = arr1 > arr2
less_than = arr1 < arr2
equal_to = arr1 == arr2

print("Greater than:\n", greater_than)
print("\nLess than:\n", less_than)
print("\nEqual to:\n", equal_to)

arr3 = np.array([1, 2, 3])
arr4 = np.array([1, 2, 3])
arr5 = np.array([1, 2, 4])

result1 = np.array_equal(arr3, arr4)
result2 = np.array_equal(arr3, arr5)

print("\nArray-wise comparison 1:", result1)
print("Array-wise comparison 2:", result2)

Greater than:
 [[False  True]
 [False False]]

Less than:
 [[ True False]
 [False  True]]

Equal to:
 [[False False]
 [ True False]]

Array-wise comparison 1: True
Array-wise comparison 2: False


In [ ]:
import sys
S = range(1000)
print("Size of each element of list in bytes:" ,sys.getsizeof(S))
print("Size of each element of list in bytes:",sys.getsizeof(S)*len(S))
D=np.arange(1000)
print("Size of each element of the numpy array in bytes:",D.itemsize)
print("Size of the whole Numpy array in bytes:",D.size*D.itemsize)

Size of each element of list in bytes: 48
Size of each element of list in bytes: 48000
Size of each element of the numpy array in bytes: 8
Size of the whole Numpy array in bytes: 8000


In [ ]:
import numpy as np

x = np.arange(10)
print("x=",x)

print("\n x[:5] = ",x[:5])
print("\n x[5:] = ",x[5:])
print("\n x[4:7] = ",x[4:7])
print("\n x[::2] = ",x[::2])
print("\n x[1::2] = ",x[1::2])
print("\n x[::-1] = ",x[::-1])
print("\n x[5::-2] = ",x[5::-2])

x= [0 1 2 3 4 5 6 7 8 9]

 x[:5] =  [0 1 2 3 4]

 x[5:] =  [5 6 7 8 9]

 x[4:7] =  [4 5 6]

 x[::2] =  [0 2 4 6 8]

 x[1::2] =  [1 3 5 7 9]

 x[::-1] =  [9 8 7 6 5 4 3 2 1 0]

 x[5::-2] =  [5 3 1]
